name: Build
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -race -v ./...
